void RussionPeasantMethodTest::run()
{
	bool tmp = true;
	try
	{
		testPow();
		if(isOk())
			std::cout<<"\tOK................testPow"<<std::endl;
		else
			std::cout<<"\tNOK...............testPow"<<std::endl;
		tmp = tmp && isOk();
		ok = true;
	}
	catch(Exceptions::Exception& ex)
	{ std::cout<<"testPow: Exception occured: " << ex <<std::endl; }
	catch(...)
	{ std::cout<<"testPow: Unknown exception"<<std::endl;  }

}
